"""Acquisition ports that keep provider JSON outside the canonical odds domain."""

from __future__ import annotations

from typing import Protocol

from .provider_models import (
    ProviderCompetition, ProviderCredentialConfig, ProviderFixture,
    ProviderMetadata, ProviderQuotaSnapshot, ProviderResponseReceipt,
)
from .models import SourceOddsEvent, SourceOddsQuote


class HistoricalOddsProviderPort(Protocol):
    credential: ProviderCredentialConfig

    def diagnose_credentials(self) -> tuple[bool, ProviderResponseReceipt | None]: ...
    def fetch_provider_metadata(self) -> ProviderMetadata: ...
    def list_supported_competitions(self) -> tuple[ProviderCompetition, ...]: ...
    def resolve_competition(self, query: str) -> ProviderCompetition | None: ...
    def list_historical_fixtures(self, competition_id: str, date_from: str, date_to: str) -> tuple[ProviderFixture, ...]: ...
    def inspect_fixture_odds_availability(self, fixture_id: str) -> bool: ...
    def fetch_fixture_odds_sample(self, fixture_id: str) -> tuple[SourceOddsEvent, tuple[SourceOddsQuote, ...]]: ...
    def inspect_quota(self) -> ProviderQuotaSnapshot: ...
