from typing import Protocol

from app.prediction_inference import PredictionInferenceResult
from app.probability_calibration import ProbabilityCalibrationConfig, ProbabilityCalibrationEngine

from .models import CalibratedMarketProbabilityAssembly, CalibrationSetDefinition


class ProbabilityCalibrationEngineFactory(Protocol):
    def build(self, config: ProbabilityCalibrationConfig) -> ProbabilityCalibrationEngine: ...


class RawInferenceReader(Protocol):
    def load_inference_by_id(self, inference_id: str) -> PredictionInferenceResult | None: ...


class CalibrationSetRepository(Protocol):
    def append_calibration_set(self, value: CalibrationSetDefinition) -> tuple[CalibrationSetDefinition, bool]: ...
    def find_calibration_set_by_id(self, calibration_set_id: str) -> CalibrationSetDefinition | None: ...
    def find_calibration_set_by_fingerprint(self, fingerprint: str) -> CalibrationSetDefinition | None: ...
    def find_active_compatible_set(self, model_artifact_id: str, model_version: str) -> CalibrationSetDefinition | None: ...
    def list_calibration_sets_for_model(self, model_artifact_id: str) -> tuple[CalibrationSetDefinition, ...]: ...


class CalibratedAssemblyRepository(Protocol):
    def append_calibrated_assembly(self, value: CalibratedMarketProbabilityAssembly) -> tuple[CalibratedMarketProbabilityAssembly, bool]: ...
    def find_by_assembly_fingerprint(self, fingerprint: str) -> CalibratedMarketProbabilityAssembly | None: ...
    def load_assembly_by_id(self, assembly_id: str) -> CalibratedMarketProbabilityAssembly | None: ...
    def find_for_inference_and_calibration_set(self, inference_id: str, calibration_set_fingerprint: str) -> CalibratedMarketProbabilityAssembly | None: ...
    def find_latest_for_match_and_model(self, match_id: str, model_artifact_id: str) -> CalibratedMarketProbabilityAssembly | None: ...
    def list_assemblies_for_inference(self, inference_id: str) -> tuple[CalibratedMarketProbabilityAssembly, ...]: ...
