"""Dependency-injected activation boundaries."""

from typing import Protocol


class ModelActivationRepository(Protocol):
    def resolve_current_champion(self, scope): ...
    def append_activation_plan(self, plan): ...
    def execute_activation(self, plan, execution_request_id, execution_timestamp, operator): ...
    def append_rollback_plan(self, plan): ...
    def execute_rollback(self, plan, execution_request_id, execution_timestamp, operator): ...


class RuntimeChampionResolverPort(Protocol):
    def resolve(self, model_scope): ...
