"""Dependency-injection contracts for immutable comparison sources and results."""

from typing import Iterator, Protocol


class ModelComparisonRepository(Protocol):
    def append_comparison_run(self, run): ...
    def find_by_comparison_run_fingerprint(self, fingerprint): ...
    def find_by_request_id(self, request_id): ...
    def load_comparison_run(self, comparison_run_id): ...
    def list_candidates(self, comparison_run_id): ...
    def list_source_evidence(self, comparison_run_id, candidate_row_id=None): ...
    def list_metric_evaluations(self, comparison_run_id, candidate_row_id=None): ...
    def list_stability_groups(self, comparison_run_id, candidate_row_id=None): ...
    def list_statistical_evidence(self, comparison_run_id, candidate_row_id=None): ...
    def list_gate_evaluations(self, comparison_run_id, candidate_row_id=None): ...
    def list_score_components(self, comparison_run_id, candidate_row_id=None): ...
    def list_recommendations(self, comparison_run_id): ...
    def list_exclusions(self, comparison_run_id): ...
    def list_comparisons_for_champion_model(self, artifact_id): ...
    def list_comparisons_for_challenger_model(self, artifact_id): ...
    def list_promotion_recommendations(self): ...
    def stream_comparison_events(self, comparison_run_id) -> Iterator: ...
