"""Dependency-injection ports for historical calibration fitting."""

from typing import Iterator, Protocol

from .models import HistoricalCalibrationCommand, PreparedCalibrationRun


class HistoricalProbabilityCalibrationRepository(Protocol):
    def append_calibration_run(self, run: PreparedCalibrationRun): ...
    def find_by_calibration_run_fingerprint(self, fingerprint: str): ...
    def find_by_request_id(self, request_id: str): ...
    def load_calibration_run(self, calibration_run_id: str): ...
    def load_calibration_artifact_set(self, artifact_set_id: str): ...
    def load_target_calibration_artifact(self, artifact_set_id: str, target_identity: str): ...
    def list_target_calibration_artifacts(self, artifact_set_id: str): ...
    def list_validation_predictions(self, calibration_run_id: str): ...
    def list_calibration_metrics(self, calibration_run_id: str): ...
    def list_reliability_bins(self, calibration_run_id: str, target_identity=None): ...
    def list_calibration_runs_for_artifact(self, artifact_id: str): ...
    def stream_calibrated_predictions(self, calibration_run_id: str) -> Iterator: ...
