"""Dependency-injection ports for historical model training."""

from typing import Iterator, Protocol

from .models import (
    ArtifactTarget, HistoricalModelTrainingCommand, ModelArtifact, PreparedTrainingRun,
    TrainingOutcome,
)


class HistoricalModelTrainingRepository(Protocol):
    def append_training_run(self, run: PreparedTrainingRun) -> None: ...
    def find_by_training_run_fingerprint(self, fingerprint: str) -> PreparedTrainingRun | None: ...
    def find_by_request_id(self, request_id: str) -> PreparedTrainingRun | None: ...
    def load_training_run(self, training_run_id: str) -> PreparedTrainingRun | None: ...
    def load_model_artifact(self, artifact_id: str) -> ModelArtifact | None: ...
    def load_artifact_target(self, artifact_id: str, target_identity: str) -> ArtifactTarget | None: ...
    def list_artifact_targets(self, artifact_id: str) -> tuple[ArtifactTarget, ...]: ...
    def list_preprocessing_features(self, artifact_id: str): ...
    def list_training_examples(self, training_run_id: str): ...
    def list_metrics(self, training_run_id: str): ...
    def list_training_runs_for_fold(self, fold_id: str): ...
    def stream_artifact_parameters(self, artifact_id: str) -> Iterator[ArtifactTarget]: ...


class HistoricalModelTrainingService(Protocol):
    def train(self, command: HistoricalModelTrainingCommand) -> TrainingOutcome: ...
