"""Dependency-injection ports for read-only sources and append-only results."""

from typing import Iterator, Protocol


class HistoricalBacktestingRepository(Protocol):
    def append_backtest_run(self, run): ...
    def find_by_backtest_run_fingerprint(self, fingerprint): ...
    def find_by_request_id(self, request_id): ...
    def load_backtest_run(self, backtest_run_id): ...
    def list_predictions(self, backtest_run_id): ...
    def list_market_assessments(self, backtest_run_id): ...
    def list_selections(self, backtest_run_id): ...
    def list_settlements(self, backtest_run_id): ...
    def list_bankroll_ledger(self, backtest_run_id): ...
    def list_metrics(self, backtest_run_id): ...
    def list_reliability_bins(self, backtest_run_id): ...
    def list_exclusions(self, backtest_run_id): ...
    def list_backtests_for_model_artifact(self, artifact_id): ...
    def list_backtests_for_calibration_artifact(self, artifact_set_id): ...
    def stream_backtest_events(self, backtest_run_id) -> Iterator: ...


class FinalScoreReader(Protocol):
    def load_final_score(self, historical_match_id: str) -> tuple[int, int] | None: ...
