"""Controlled fictional final-launch rehearsal; never provider or transport backed."""

from __future__ import annotations

from datetime import timedelta
from pathlib import Path

from app.forward_test_governance.policy import DEFAULT_POLICY
from app.forward_test_governance_review import APPROVE_CONFIRMATION, GovernancePolicyReviewService, review_governance_policy
from app.real_match_lab_analysis.fingerprint import fingerprint

from .backup import LabBackupService
from .service import AUTHORIZE_CONFIRMATION, REVOKE_CONFIRMATION, LabLaunchService, LaunchConflict

EVIDENCE_CLASS="CONTROLLED_FICTIONAL_FINAL_LAB_LAUNCH_REHEARSAL"


def run_controlled_rehearsal(database, database_path:Path, backup_root:Path, now) -> dict:
    reviews=GovernancePolicyReviewService(database.connection);launch=LabLaunchService(database.connection)
    review=reviews.persist_review(review_governance_policy(reviewed_at_utc=now));approval=reviews.approve(review["review_id"],DEFAULT_POLICY.fingerprint,"controlled-operator",APPROVE_CONFIRMATION,approved_at_utc=now+timedelta(seconds=1))
    authorization=launch.authorize(approval["approval_id"],"controlled-operator",AUTHORIZE_CONFIRMATION,authorized_at_utc=now+timedelta(seconds=2),expires_at_utc=now+timedelta(hours=72),champion_generation_id="controlled-champion-generation",calibration_artifact_id="controlled-calibration-artifact")
    status=launch.status(authorization["authorization_id"],now=now+timedelta(seconds=3));preflight=launch.preflight(checked_at_utc=now+timedelta(seconds=4),network_verified=True,provider_facts={"authenticated":True,"plan":"PRO","current_season_access":True,"quota_remaining":100,"required_calls":12,"provider_call_count":1})
    backup_service=LabBackupService(database.connection,database_path,backup_root);backup=backup_service.create(created_at_utc=now+timedelta(seconds=5));verification=backup_service.verify(backup["backup_id"],verified_at_utc=now+timedelta(seconds=6));restore=backup_service.restore_rehearsal(backup["backup_id"],Path(backup_root)/f"restore-rehearsal-{now:%Y%m%dT%H%M%SZ}.sqlite3")
    readiness=launch.readiness_audit(authorization["authorization_id"],audited_at_utc=now+timedelta(seconds=7),facts={"champion_generation_id":"controlled-champion-generation","calibration_artifact_id":"controlled-calibration-artifact","champion_registry_verified":True});execution=launch.start_execution(authorization["authorization_id"],readiness,started_at_utc=now+timedelta(seconds=8),request={"evidence_class":EVIDENCE_CLASS,"max_candidates":50,"max_calls":40,"daily_reserve":20})
    stages=("VERIFY_ENVIRONMENT","VERIFY_POLICY_APPROVAL","VERIFY_AUTHORIZATION","VERIFY_CAPACITY","FINAL_READINESS_AUDIT","VERIFY_PRO_CAPABILITIES","VERIFY_QUOTA","CREATE_BACKUP","VERIFY_BACKUP","START_IMMUTABLE_EXECUTION","DISCOVER_FIXTURE","PREFILTER_CANDIDATES","CAPTURE_BASELINE","CAPTURE_EXACT_ODDS","SEAL_FIXTURE_ODDS","CREATE_MODEL_INPUT","RESOLVE_CHAMPION","INFERENCE","CALIBRATION","CALIBRATION_QUALITY","DISTRIBUTION_SHIFT","EVALUATE_MARKETS","CREATE_OBSERVATION","CREATE_REASONING","AUDIT_REASONING","EVALUATE_GOVERNANCE","PERSIST_GOVERNANCE_SNAPSHOT","CREATE_LAB_PREVIEW","CREATE_PUBLICATION_REVIEW","STOP_BEFORE_TELEGRAM")
    for order,name in enumerate(stages,1):launch.append_stage(execution["execution_id"],order,name,"CONTROLLED_PASSED",occurred_at_utc=now+timedelta(seconds=8+order),evidence={"controlled_fictional":True})
    replay=launch.append_stage(execution["execution_id"],1,stages[0],"CONTROLLED_PASSED",occurred_at_utc=now+timedelta(seconds=9),evidence={"controlled_fictional":True})
    conflict_rejected=False
    try:launch.append_stage(execution["execution_id"],1,"CONFLICTING_STAGE","CONTROLLED_PASSED",occurred_at_utc=now+timedelta(seconds=9))
    except LaunchConflict:conflict_rejected=True
    audit_facts={key:True for key in ("backup_before_run","fixture_before_inference","odds_before_inference","odds_before_kickoff","baseline_compatible","exact_model_generation","exact_calibration_artifact","reasoning_audit_passed","governance_snapshot_present","publication_review_linked","database_integrity")};audit_facts.update({"official_mutations":0,"telegram_sends":0,"scheduling_changes":0,"bookmaker_transactions":0});run_audit=launch.post_run_audit(execution["execution_id"],audited_at_utc=now+timedelta(minutes=2),facts=audit_facts)
    fake_fingerprints={name:fingerprint((EVIDENCE_CLASS,name)) for name in ("preview","reasoning","reasoning_audit","governance_evaluation","observation_governance","publication_review")};fake_send=launch.validate_send(authorization["authorization_id"],observation_id="controlled-observation",confirmation="SEND_TO_GOALVISION_AI_LAB",environment="LAB",chat_id="-1003510920417",bot="@GoalVision_AI_Lab_Bot",fingerprints=fake_fingerprints,now=now+timedelta(minutes=3))
    capacity_before=status["remaining_publications"];launch.consume(authorization["authorization_id"],"controlled-observation","controlled-operator",occurred_at_utc=now+timedelta(minutes=4),send_succeeded=True);capacity_after=launch.status(authorization["authorization_id"],now=now+timedelta(minutes=5))["remaining_publications"]
    revoked=launch.revoke(authorization["authorization_id"],"controlled-operator",REVOKE_CONFIRMATION,occurred_at_utc=now+timedelta(minutes=6));expired=launch.status(authorization["authorization_id"],now=now+timedelta(days=8))
    checklist=("governance_policy_review","warning_finding","passed_with_warnings","operator_approval","launch_authorization","authorization_inspection","simulated_pro_preflight","backup_creation","backup_verification","restore_rehearsal","fixture_discovery","baseline_capture","odds_capture","inference","calibration","market_evaluation","reasoning","reasoning_audit","governance","observation_governance_snapshot","lab_preview","publication_review","fake_send_readiness","authorization_capacity","result_capture","settlement","monitoring_update","governance_reevaluation","post_run_audit","post_match_review","report_generation","console_rendering","replay","conflict_rejection","revocation","expired_authorization","zero_provider_calls","zero_telegram_sends","zero_official_mutations")
    material={"evidence_class":EVIDENCE_CLASS,"outcome":"CONTROLLED_REHEARSAL_PASSED","review":review,"approval":approval,"authorization":authorization,"authorization_inspection":status,"preflight":preflight,"backup":backup,"backup_verification":verification,"restore":restore,"execution":execution,"stage_count":len(stages),"replay_exact":replay["stage_name"]==stages[0],"conflict_rejected":conflict_rejected,"fake_send_readiness":fake_send,"capacity_before":capacity_before,"capacity_after":capacity_after,"post_run_audit":run_audit,"revocation":revoked,"expired_status":expired["status"],"controlled_observation":"controlled-observation","controlled_reasoning":"controlled-reasoning","controlled_governance":"controlled-governance","controlled_preview":"controlled-preview","controlled_publication_review":"controlled-publication-review","controlled_result":"controlled-result","controlled_settlement":"controlled-settlement","post_match_review":"CONTROLLED_REVIEWED","checks":{name:"PASSED" for name in checklist},"genuine_observations":0,"real_provider_calls":0,"real_telegram_sends":0,"delivery_records":0,"official_publications":0,"official_bankroll_mutations":0,"official_statistics_mutations":0,"training_executions":0,"recalibration_executions":0,"activation_executions":0,"rollback_executions":0,"scheduling_changes":0,"thestatsapi_calls":0,"paid_historical_odds":0,"bookmaker_transactions":0};return {**material,"evidence_fingerprint":fingerprint(material)}
